spring.jpa:
  hibernate:
    ddl-auto: create

  show-sql: true
  open-in-view: true

  properties:
    hibernate.format_sql: true

spring:
  data:
    redis:
      host: localhost
      port: 6379


spring.datasource:
  url: jdbc:mysql://localhost:3306/cryptocurrency_simulated_investment
  username: csiuser
  password: dptmzbdpfrhdqn3#
  driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    web: debug

