# Jpa
spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  open-in-view: true
  properties:
    hibernate.format_sql: true

# Redis
spring.data:
    redis:
      host: localhost
      port: 6379

# Mysql
spring.datasource:
  url: jdbc:mysql://localhost:3306/cryptocurrency_simulated_investment
  username: csiuser
  password: dptmzbdpfrhdqn3#
  driver-class-name: com.mysql.cj.jdbc.Driver

# Logging
logging:
  level:
    web: debug

# Quartz
spring.quartz:
    job-store-type: jdbc
    jdbc.initialize-schema: always

# Security

jwt:
  secret: abcdefghijklmnOPQRSTUVWXYZ