# Jpa
spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  open-in-view: true
  properties:
    hibernate.format_sql: true

# Local
## Redis
#spring.data:
#    redis:
#      host: localhost
#      port: 6379
#
## Mysql
#spring.datasource:
#  url: jdbc:mysql://localhost:3306/frincoin
#  username: coinuser
#  password: dptmzbdpfrhdqn3#
#  driver-class-name: com.mysql.cj.jdbc.Driver

# Deploy Server
# Redis
spring.data:
  redis:
    host: redis-container
    port: 6379

# Mysql
spring.datasource:
  url: jdbc:mysql://mysql-container:3306/frincoin
  username: coinuser
  password: dptmzbdpfrhdqn3#
  driver-class-name: com.mysql.cj.jdbc.Driver

# Logging
logging:
  level:
    web: debug
    org:
      springframework:
        security: TRACE

# Quartz
spring.quartz:
    job-store-type: jdbc
    jdbc.initialize-schema: always
    properties:
      org.quartz.threadPool.threadNamePrefix: quartz-worker

# mail
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: frincoin000@gmail.com
    password: itgiespzcgrwuuci
    properties:
      mail:
        debug: true
        transport.protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  validation:
    timeout: 120

# val
jwt:
  secret: 9d0u1hsdfuh109238478019dhuA
  symmetric: 3i3918dhfapsdoia983soifoi
regex:
  password: ^(?=.*[a-z].*)(?=.*[A-Z].*)(?=.*[0-9].*)(?=.*[!@#$%^&*].*).{8,}$
  username: ^[가-힣a-zA-Z]{6,20}$

crypto:
  redis:
    time: 600

# mail
mail:
  validation:
    # validation code resend time(second) interval
    resend: 120
    # validation expire time(second)
    expire: 600